name: Package & Release
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set release version
        run: echo "RELEASE_VERSION=$(date +%s)" >> $GITHUB_ENV

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.0.${{ env.RELEASE_VERSION }}
          release_name: Shader Replacer version 1.0.${{ env.RELEASE_VERSION }}
          body: Released by Package Repository Assets and Upload workflow.
          draft: false
          prerelease: false

      - name: Create ShaderReplacer.zip archive
        run: |
          zip -r ShaderReplacer.zip ShaderFixes shader_replace.addon

      - name: Upload ShaderReplacer.zip archive
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./ShaderReplacer.zip
          asset_name: ShaderReplacer.zip
          asset_content_type: application/zip
